'use client';

import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';

type Station={id:string;name:string;city:string;address?:string;distanceKm:number;routeOffsetKm?:number;price:number;waitMin:number;detourMin:number;lat?:number;lon?:number;arrivalHour?:number;arrivalMinute?:number;services?:string[];serviceCategories?:string[];flowayContextScore?:number;smartContext?:{message:string;intent?:string};sources?:{station?:string;priceFreshness?:string;wait?:string};waitModel?:{label:string;confidence:string;factors:string[]}};
type RouteData={origin:{label:string;lat?:number;lon?:number};destination:{label:string;lat?:number;lon?:number};distanceKm:number;durationMin:number;stations:Station[];fuel:string;geometry?:{coordinates:[number,number][]}};
type Filter='Tous'|'Restauration'|'Café'|'Boutique'|'Toilettes';
type Intent='Auto'|'Manger'|'Café'|'Carburant'|'Recharge'|'Toilettes';
type LivePosition={lat:number;lon:number;accuracy:number;speed:number|null;updatedAt:number};

const serviceIcon=(s:string)=>s==='Restauration'?'🍴':s==='Café'?'☕':s==='Boutique'?'🛍':s==='Toilettes'?'🚻':s==='Recharge VE'?'⚡':s==='Douches'?'🚿':s==='Wi-Fi'?'📶':'⛽';
const short=(s:string)=>s.split(',')[0];
const duration=(m=0)=>{const h=Math.floor(m/60),r=Math.max(0,Math.round(m%60));return h?`${h} h ${String(r).padStart(2,'0')}`:`${r} min`};
const clock=(s?:Station)=>s?.arrivalHour==null?'--:--':`${String(s.arrivalHour).padStart(2,'0')}:${String(s.arrivalMinute||0).padStart(2,'0')}`;
const localDateTime=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const toRad=(n:number)=>n*Math.PI/180;
function haversine(a:[number,number],b:[number,number]){const R=6371,dLat=toRad(b[1]-a[1]),dLon=toRad(b[0]-a[0]),la1=toRad(a[1]),la2=toRad(b[1]);const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h));}
function cumulative(coords:[number,number][]){const out=[0];for(let i=1;i<coords.length;i++)out[i]=out[i-1]+haversine(coords[i-1],coords[i]);return out;}
function intentCategory(intent:Intent){return intent==='Manger'?'Restauration':intent==='Recharge'?'Recharge VE':intent==='Carburant'?'Carburant':intent;}
function score(s:Station,intent:Intent){let value=s.waitMin+s.detourMin+s.price*2-(s.flowayContextScore||0);if(intent!=='Auto'){const cat=intentCategory(intent);const match=cat==='Carburant'||s.serviceCategories?.includes(cat);value+=match?-15:25;}return value;}

export default function FlowayV3(){
 const [origin,setOrigin]=useState('Paris'); const [destination,setDestination]=useState('Lyon');
 const [draftOrigin,setDraftOrigin]=useState('Paris'); const [draftDestination,setDraftDestination]=useState('Lyon');
 const [departure,setDeparture]=useState(localDateTime()); const [draftDeparture,setDraftDeparture]=useState(localDateTime());
 const [fuel,setFuel]=useState('Gazole'); const [route,setRoute]=useState<RouteData|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const [editing,setEditing]=useState(false); const [selected,setSelected]=useState<Station|null>(null); const [filter,setFilter]=useState<Filter>('Tous'); const [intent,setIntent]=useState<Intent>('Auto'); const [startAfter,setStartAfter]=useState(120);
 const [live,setLive]=useState<LivePosition|null>(null); const [gpsState,setGpsState]=useState<'off'|'requesting'|'on'|'error'>('off'); const [gpsError,setGpsError]=useState(''); const watchRef=useRef<number|null>(null);

 async function loadRoute(from:string,to:string,nextFuel=fuel,when=departure){setLoading(true);setError('');try{const iso=new Date(when).toISOString();const r=await fetch(`/api/route?origin=${encodeURIComponent(from)}&destination=${encodeURIComponent(to)}&fuel=${encodeURIComponent(nextFuel)}&departureAt=${encodeURIComponent(iso)}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Calcul impossible');setRoute(j);setOrigin(j.origin.label);setDestination(j.destination.label);setDeparture(when);setStartAfter(Math.min(Math.max(120,Math.round(j.distanceKm*.48/10)*10),Math.max(0,Math.floor(j.distanceKm-50))));}catch(e){setError(e instanceof Error?e.message:'Impossible de calculer cet itinéraire.')}finally{setLoading(false)}}
 useEffect(()=>{const now=localDateTime();setDeparture(now);setDraftDeparture(now);void loadRoute('Paris','Lyon','Gazole',now);return()=>{if(watchRef.current!==null&&typeof navigator!=='undefined'&&navigator.geolocation)navigator.geolocation.clearWatch(watchRef.current)}},[]);

 function startGps(){if(typeof navigator==='undefined'||!navigator.geolocation){setGpsState('error');setGpsError('Géolocalisation non disponible sur cet appareil.');return}if(watchRef.current!==null){navigator.geolocation.clearWatch(watchRef.current);watchRef.current=null;setGpsState('off');setLive(null);return}setGpsState('requesting');setGpsError('');watchRef.current=navigator.geolocation.watchPosition(p=>{setLive({lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy,speed:p.coords.speed,updatedAt:p.timestamp});setGpsState('on')},e=>{setGpsState('error');setGpsError(e.code===1?'Autorise la localisation dans ton navigateur pour activer le mode trajet.':'Position GPS momentanément indisponible.')},{enableHighAccuracy:true,maximumAge:5000,timeout:12000});}

 const stations=useMemo(()=>[...(route?.stations||[])].sort((a,b)=>a.distanceKm-b.distanceKm),[route]);
 const liveProgress=useMemo(()=>{if(!live||!route?.geometry?.coordinates?.length)return null;const coords=route.geometry.coordinates;const cum=cumulative(coords);let idx=0,best=Infinity;for(let i=0;i<coords.length;i++){const d=haversine([live.lon,live.lat],coords[i]);if(d<best){best=d;idx=i}}return {km:Math.min(route.distanceKm,cum[idx]),offRouteKm:best,remainingKm:Math.max(0,route.distanceKm-cum[idx])}},[live,route]);
 const effectiveStart=Math.max(startAfter,liveProgress?.km||0);
 const eligible=useMemo(()=>stations.filter(s=>s.distanceKm>=effectiveStart&&(filter==='Tous'||s.serviceCategories?.includes(filter))),[stations,effectiveStart,filter]);
 const best=useMemo(()=>[...eligible].sort((a,b)=>score(a,intent)-score(b,intent))[0],[eligible,intent]);
 const first=eligible[0]; const saved=best&&first?Math.max(0,first.waitMin+first.detourMin-best.waitMin-best.detourMin):0; const pauses=route?Math.max(0,Math.floor((route.durationMin-1)/120)):0;
 const sampled=useMemo(()=>{if(!stations.length||!route)return[] as Station[];return [.16,.32,.48,.64,.82].map(r=>stations.reduce((a,b)=>Math.abs(b.distanceKm-route.distanceKm*r)<Math.abs(a.distanceKm-route.distanceKm*r)?b:a,stations[0])).filter((s,i,a)=>a.findIndex(x=>x.id===s.id)===i)},[stations,route]);
 async function submit(e:FormEvent){e.preventDefault();await loadRoute(draftOrigin.trim(),draftDestination.trim(),fuel,draftDeparture);setEditing(false)}
 const eta=route?duration(route.durationMin+pauses*15):'—'; const bestTravel=best&&route?duration(Math.max(0,Math.round((best.distanceKm-(liveProgress?.km||0))/Math.max(route.distanceKm,1)*route.durationMin))):'—';

 return <main className="v3app">
  <header className="v3top"><button className="v3icon">☰</button><div className="v3brand"><span>≋</span><strong>Floway</strong><small>CHAQUE PAUSE COMPTE</small></div><div className="v3status"><button>🔔<b>2</b></button><span>● Trafic fluide</span><span>☀ 18°C</span></div></header>
  {error&&<div className="v3error">{error}</div>}
  <section className="v3livebar"><div><span className={gpsState==='on'?'liveDot on':'liveDot'}/><strong>{gpsState==='on'?'MODE TRAJET ACTIF':'LOCALISATION MOBILE'}</strong><small>{liveProgress?`${Math.round(liveProgress.km)} km parcourus · ${Math.round(liveProgress.remainingKm)} km restants`:gpsError||'Active le GPS pour que Floway s’adapte à ta position réelle.'}</small></div><div className="liveMeta">{live&&<><span>± {Math.round(live.accuracy)} m</span>{live.speed!=null&&<span>{Math.round(live.speed*3.6)} km/h</span>}</>}</div><button onClick={startGps}>{gpsState==='requesting'?'LOCALISATION…':gpsState==='on'?'ARRÊTER LE SUIVI':'ACTIVER LE SUIVI GPS'}</button></section>

  <section className="v3topgrid"><article className="v3hero"><div className="v3heroshade"/><div className="v3heroContent"><span className="v3hello">Bonjour 👋</span><h1>Prêt pour<br/>une belle route ?</h1><button className="v3routeTitle" onClick={()=>setEditing(true)}>{short(origin)} <i>→</i> {short(destination)} <em>✎</em></button><button className="v3modifyRoute" onClick={()=>setEditing(true)}>MODIFIER L’ITINÉRAIRE</button><div className="v3heroMetrics"><div><b>{route?Math.round(route.distanceKm):'—'} km</b><small>Distance</small></div><div><b>{route?duration(route.durationMin):'—'}</b><small>Durée estimée</small></div><div><b>{pauses}</b><small>Pauses conseillées</small></div></div><button className="v3full" onClick={()=>route&&setStartAfter(Math.min(Math.round(route.distanceKm*.55/10)*10,Math.max(0,route.distanceKm-60)))}>DÉPART AVEC LE PLEIN ⛽</button></div><div className="v3miniRoute"><span>{short(origin)}</span><span>{short(destination)}</span><div className="v3track"><i/><b className="v3car" style={liveProgress&&route?{left:`${Math.min(94,Math.max(3,liveProgress.km/route.distanceKm*100))}%`}:undefined}>🚙</b>{sampled.slice(0,3).map((s,i)=><button key={s.id} style={{left:`${35+i*18}%`}} onClick={()=>setSelected(s)}>{serviceIcon(s.serviceCategories?.[0]||'')}</button>)}<i/></div><small>{liveProgress?`${Math.round(liveProgress.km)} km`:'0 km'}</small><small>{route?Math.round(route.distanceKm):0} km</small></div></article>
   <aside className="v3feed"><div className="v3panelHead"><div><span>FIL DU VOYAGE</span><h2>Toutes les stations sur l’itinéraire</h2></div><b>{stations.length} stations</b></div><div className="v3vertical"><i className="v3line"/><div className="v3end"><i/><strong>{liveProgress?'Votre position':short(origin)}</strong><small>{liveProgress?`${Math.round(liveProgress.km)} km parcourus`:'0 km'}</small></div>{sampled.filter(s=>s.distanceKm>=(liveProgress?.km||0)).map(s=><button key={s.id} className={best?.id===s.id?'v3feedStop recommended':'v3feedStop'} onClick={()=>setSelected(s)}><span>{serviceIcon(s.serviceCategories?.[0]||'')}</span><div><strong>{s.city||s.name}</strong><small>{Math.round(s.distanceKm)} km · {clock(s)}</small></div>{best?.id===s.id&&<em>FLOWAY AI ✦</em>}</button>)}<div className="v3end bottom"><i/><strong>{short(destination)}</strong><small>{route?Math.round(route.distanceKm):0} km · arrivée</small></div></div><button className="v3ghost" onClick={()=>document.getElementById('v3stations')?.scrollIntoView({behavior:'smooth'})}>VOIR TOUTES LES STATIONS</button></aside></section>

  <section className="v3intent"><div><span>QUE CHERCHES-TU POUR TA PROCHAINE PAUSE ?</span><h2>{intent==='Auto'?'Floway choisit selon l’heure et le trajet':intent==='Manger'?'Priorité à la restauration':intent==='Recharge'?'Priorité aux bornes de recharge':`Priorité : ${intent.toLowerCase()}`}</h2></div><div className="intentChips">{(['Auto','Manger','Café','Carburant','Recharge','Toilettes'] as Intent[]).map(x=><button key={x} className={intent===x?'active':''} onClick={()=>setIntent(x)}>{x==='Auto'?'✨':x==='Manger'?'🍴':x==='Café'?'☕':x==='Carburant'?'⛽':x==='Recharge'?'⚡':'🚻'} {x==='Auto'?'Floway choisit':x}</button>)}</div></section>

  <section className="v3midgrid"><article className="v3recommend"><div className="v3stopImage"><span>PROCHAINE PAUSE RECOMMANDÉE</span><button>♡</button></div><div className="v3stopInfo"><div><h2>Aire de<br/>{best?(best.city||best.name):'—'}</h2><div className="v3services">{(best?.serviceCategories||['Carburant','Restauration','Café','Toilettes']).slice(0,7).map(s=><span key={s}><i>{serviceIcon(s)}</i>{s}</span>)}</div></div><aside><b>{best?`Dans ${Math.max(0,Math.round(best.distanceKm-(liveProgress?.km||0)))} km`:'—'}</b><strong>{bestTravel}</strong><small>{liveProgress?'depuis votre position':`depuis ${short(origin)}`}</small><ul><li>{intent==='Auto'?'Contexte horaire analysé':`Priorité ${intent.toLowerCase()}`}</li><li>{best?.services?.length||0} services recensés</li><li>Attente optimisée</li></ul><button onClick={()=>best&&setSelected(best)}>VOIR LE DÉTAIL</button></aside></div></article>
   <article className="v3ai"><div className="v3panelHead"><div><span>FLOWAY AI</span><h2>Optimisé pour vous</h2></div><b>✦</b></div><div className="v3orb"><i/><i/><i/><strong>✦</strong></div><h3>{best?'Votre meilleur arrêt est déjà identifié.':'Floway analyse votre trajet.'}</h3><p>{best?.smartContext?.message||'Floway croise heure de passage, position réelle, détour, attente, carburant et services pour recommander le meilleur arrêt.'}</p><div className="v3aiStats"><div><small>TEMPS GAGNÉ</small><b>≈ {saved} min</b></div><div><small>DÉTOUR</small><b>{best?`+${best.detourMin} min`:'—'}</b></div><div><small>ATTENTE</small><b>{best?`${best.waitMin} min`:'—'}</b></div></div></article></section>

  <section className="v3planner"><div><span>QUAND VEUX-TU COMMENCER À CHERCHER ?</span><h2>Après {Math.round(startAfter)} km · environ {route?duration(Math.round(startAfter/Math.max(route.distanceKm,1)*route.durationMin)):'—'}</h2></div><button onClick={()=>route&&setStartAfter(Math.round(route.distanceKm*.55/10)*10)}>Départ avec le plein</button><input type="range" min="0" max={Math.max(50,Math.floor(route?.distanceKm||500))} step="10" value={startAfter} onChange={e=>setStartAfter(Number(e.target.value))}/><div className="v3chips">{(['Tous','Restauration','Café','Boutique','Toilettes'] as Filter[]).map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div></section>
  <section className="v3featuregrid"><article className="photo"><span>PAUSES INTELLIGENTES</span><h3>Au bon moment,<br/>au bon endroit.</h3></article><article><span>COMMUNAUTÉ ACTIVE</span><h3>Avis, photos et conseils<br/>de voyageurs.</h3><div className="v3avatars"><i>👨</i><i>👩</i><i>🧔</i><b>★ 4,8</b></div></article><article><span>POUR TOUS LES VÉHICULES</span><h3>Thermique · Électrique<br/>ou Hybride.</h3><div className="v3vehicle">⛽ ⚡ 🔌</div></article><article><span>TEMPS OPTIMISÉ</span><h3>{eta}<br/>voyage Floway</h3><strong>+{pauses*15} min de pauses utiles</strong></article></section>
  <section className="v3stations" id="v3stations"><div className="v3panelHead"><div><span>ARRÊTS DEVANT VOUS APRÈS {Math.round(effectiveStart)} KM</span><h2>Toutes les stations</h2></div><select value={fuel} onChange={e=>{setFuel(e.target.value);void loadRoute(origin,destination,e.target.value,departure)}}><option>Gazole</option><option>SP95-E10</option><option>SP98</option><option>E85</option></select></div><div className="v3cards">{eligible.slice(0,24).map(s=><button key={s.id} onClick={()=>setSelected(s)}><span>{serviceIcon(s.serviceCategories?.[0]||'')}</span><div><strong>{s.city||s.name}</strong><small>{Math.max(0,Math.round(s.distanceKm-(liveProgress?.km||0)))} km devant · {clock(s)}</small><em>{(s.serviceCategories||[]).slice(0,3).join(' · ')}</em></div><b>{s.waitMin} min</b></button>)}</div></section>
  <nav className="v3nav"><button className="active">⌁<span>ROUTE</span></button><button onClick={()=>document.getElementById('v3stations')?.scrollIntoView({behavior:'smooth'})}>⛽<span>STATIONS</span></button><a href="/ev">✦<span>FLOWAY AI</span></a><button>◉<span>COMMUNAUTÉ</span></button><button>○<span>PROFIL</span></button></nav>

  {editing&&<div className="v3overlay" onClick={()=>!loading&&setEditing(false)}><form className="v3modal" onSubmit={submit} onClick={e=>e.stopPropagation()}><span>NOUVEL ITINÉRAIRE</span><h2>Où va-t-on ?</h2><label>Départ<input value={draftOrigin} onChange={e=>setDraftOrigin(e.target.value)} required/></label><label>Destination<input value={draftDestination} onChange={e=>setDraftDestination(e.target.value)} required/></label><label>Heure de départ<input type="datetime-local" value={draftDeparture} onChange={e=>setDraftDeparture(e.target.value)} required/></label><button disabled={loading}>{loading?'ANALYSE…':'ANALYSER LE TRAJET →'}</button></form></div>}

  {selected&&<div className="v3overlay" onClick={()=>setSelected(null)}><article className="v3detail" onClick={e=>e.stopPropagation()}><button className="v3close" onClick={()=>setSelected(null)}>←</button><div className="v3detailImage"><span>FICHE ARRÊT FLOWAY</span></div><div className="v3detailBody"><span className="detailEyebrow">STATION / AIRE SUR VOTRE ITINÉRAIRE</span><h2>{selected.name}</h2><p>{selected.address&&`${selected.address} · `}{selected.city} · {Math.max(0,Math.round(selected.distanceKm-(liveProgress?.km||0)))} km devant · passage {clock(selected)}</p><div className="v3detailStats"><div><small>ATTENTE</small><b>{selected.waitMin} min</b></div><div><small>PRIX {fuel.toUpperCase()}</small><b>{selected.price?`${selected.price.toFixed(3)} €/L`:'—'}</b></div><div><small>DÉTOUR</small><b>+{selected.detourMin} min</b></div></div><h3 className="detailSectionTitle">SERVICES DISPONIBLES</h3><div className="v3services rich">{(selected.serviceCategories||[]).map(s=><span key={s}><i>{serviceIcon(s)}</i>{s}</span>)}</div>{selected.services?.length?<><h3 className="detailSectionTitle">DÉTAIL DES SERVICES RECENSÉS</h3><div className="rawServices">{selected.services.map(s=><span key={s}>{s}</span>)}</div></>:null}<div className="restaurantCallout"><div>🍴</div><div><strong>La restauration peut décider de l’arrêt</strong><p>{selected.serviceCategories?.includes('Restauration')?'Cette aire dispose d’une offre de restauration recensée. Floway la valorise davantage aux heures de repas.':'Aucune restauration détaillée n’est encore recensée ici : Floway évitera de surévaluer cet arrêt si votre priorité est de manger.'}</p></div></div><div className="v3detailAI"><span>FLOWAY AI ✦</span><p>{selected.smartContext?.message||'Cet arrêt est analysé selon votre heure de passage, votre position, le détour, l’attente et les services disponibles.'}</p>{selected.waitModel?.factors?.length?<ul>{selected.waitModel.factors.map(f=><li key={f}>{f}</li>)}</ul>:null}</div>{selected.sources&&<div className="detailSources"><small>Données station : {selected.sources.station||'source publique'}</small><small>Prix : {selected.sources.priceFreshness||'mise à jour disponible'}</small><small>Attente : {selected.sources.wait||'estimation Floway'}</small></div>}<button className="v3choose" onClick={()=>setSelected(null)}>CHOISIR CET ARRÊT →</button></div></article></div>}
 </main>
}
