'use client';

import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import OriginField from './origin-field';
import { placeLabel } from './lib/place-label';

type Station={id:string;name:string;brand?:string;city:string;address?:string;distanceKm:number;routeOffsetKm?:number;price:number;waitMin:number;detourMin:number;lat?:number;lon?:number;arrivalHour?:number;arrivalMinute?:number;services?:string[];serviceCategories?:string[];flowayContextScore?:number;smartContext?:{message:string;intent?:string};sources?:{station?:string;priceFreshness?:string;wait?:string};waitModel?:{label:string;confidence:string;measured?:boolean;factors:string[]};priceQuality?:{updatedAt?:string|null;ageHours?:number|null;status?:string;confidence?:string}};
type RouteData={origin:{label:string;lat?:number;lon?:number};destination:{label:string;lat?:number;lon?:number};distanceKm:number;durationMin:number;baseDurationMin?:number;stations:Station[];fuel:string;geometry?:{coordinates:[number,number][]};traffic?:{live:boolean;label:string;delayMin:number|null;source?:string|null}};
type Filter='Tous'|'Restauration'|'Café'|'Boutique'|'Toilettes';
type Intent='Auto'|'Manger'|'Café'|'Carburant'|'Recharge'|'Toilettes';
type LivePosition={lat:number;lon:number;accuracy:number;speed:number|null;updatedAt:number};
type Vehicle={brand:string;model:string;year:string;engine:string;tankL:number;consumption:number;fuelPct:number;reserveKm:number};
type JourneyEvent={station:Station;kind:string;label:string};
type SafetyIncident={id:string;label:string;icon:string;description:string;delayMin?:number|null;lat?:number|null;lon?:number|null;roads?:string[]};

const serviceIcon=(s:string)=>s==='Restauration'?'🍴':s==='Café'?'☕':s==='Boutique'?'🛍':s==='Toilettes'?'🚻':s==='Recharge VE'?'⚡':s==='Douches'?'🚿':s==='Wi-Fi'?'📶':'⛽';
const duration=(m=0)=>{const h=Math.floor(m/60),r=Math.max(0,Math.round(m%60));return h?`${h} h ${String(r).padStart(2,'0')}`:`${r} min`};
const clock=(s?:Station)=>s?.arrivalHour==null?'--:--':`${String(s.arrivalHour).padStart(2,'0')}:${String(s.arrivalMinute||0).padStart(2,'0')}`;
const localDateTime=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)};
const toRad=(n:number)=>n*Math.PI/180;
const defaultVehicle:Vehicle={brand:'Volkswagen',model:'Tiguan',year:'2014',engine:'2.0 TDI',tankL:64,consumption:6.5,fuelPct:75,reserveKm:80};
function haversine(a:[number,number],b:[number,number]){const R=6371,dLat=toRad(b[1]-a[1]),dLon=toRad(b[0]-a[0]),la1=toRad(a[1]),la2=toRad(b[1]);const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h));}
function cumulative(coords:[number,number][]){const out=[0];for(let i=1;i<coords.length;i++)out[i]=out[i-1]+haversine(coords[i-1],coords[i]);return out;}
function intentCategory(intent:Intent){return intent==='Manger'?'Restauration':intent==='Recharge'?'Recharge VE':intent==='Carburant'?'Carburant':intent;}
function score(s:Station,intent:Intent){let value=s.waitMin+s.detourMin+s.price*2-(s.flowayContextScore||0);if(intent!=='Auto'){const cat=intentCategory(intent);const match=cat==='Carburant'||s.serviceCategories?.includes(cat);value+=match?-25:80;}return value;}
function crowd(wait=0){return wait<=4?{label:'Faible',icon:'🟢'}:wait<=7?{label:'Modérée',icon:'🟠'}:{label:'Forte',icon:'🔴'};}
function eventLabel(kind:string){return kind==='Restauration'?'Repas':kind==='Café'?'Pause café':kind==='Recharge VE'?'Recharge':kind==='Toilettes'?'Pause':kind==='Carburant'?'Ravitaillement':'Arrêt';}

export default function FlowayV3(){
 const [origin,setOrigin]=useState('Paris'); const [destination,setDestination]=useState('Lyon');
 const [draftOrigin,setDraftOrigin]=useState('Paris'); const [draftDestination,setDraftDestination]=useState('Lyon');
 const [departure,setDeparture]=useState(localDateTime()); const [draftDeparture,setDraftDeparture]=useState(localDateTime());
 const [fuel,setFuel]=useState('Gazole'); const [route,setRoute]=useState<RouteData|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const [editing,setEditing]=useState(false); const [selected,setSelected]=useState<Station|null>(null); const [filter,setFilter]=useState<Filter>('Tous'); const [intent,setIntent]=useState<Intent>('Manger');
 const [vehicle,setVehicle]=useState<Vehicle>(defaultVehicle); const [vehicleOpen,setVehicleOpen]=useState(false); const [hydrated,setHydrated]=useState(false);
 const [live,setLive]=useState<LivePosition|null>(null); const [gpsState,setGpsState]=useState<'off'|'requesting'|'on'|'error'>('off'); const [gpsError,setGpsError]=useState(''); const watchRef=useRef<number|null>(null);
 const [navOpen,setNavOpen]=useState(false); const [safetyConnected,setSafetyConnected]=useState(false); const [safetyIncidents,setSafetyIncidents]=useState<SafetyIncident[]>([]); const [safetyUpdatedAt,setSafetyUpdatedAt]=useState<string|null>(null);

 async function loadRoute(from:string,to:string,nextFuel=fuel,when=departure){setLoading(true);setError('');try{const iso=new Date(when).toISOString();const r=await fetch(`/api/route?origin=${encodeURIComponent(from)}&destination=${encodeURIComponent(to)}&fuel=${encodeURIComponent(nextFuel)}&departureAt=${encodeURIComponent(iso)}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Calcul impossible');setRoute(j);setOrigin(j.origin.label);setDestination(j.destination.label);setDeparture(when);}catch(e){setError(e instanceof Error?e.message:'Impossible de calculer cet itinéraire.')}finally{setLoading(false)}}
 useEffect(()=>{const now=localDateTime();setDeparture(now);setDraftDeparture(now);try{const savedIntent=localStorage.getItem('floway:intent') as Intent|null;const savedVehicle=localStorage.getItem('floway:vehicle');if(savedIntent)setIntent(savedIntent);if(savedVehicle)setVehicle({...defaultVehicle,...JSON.parse(savedVehicle)});}catch{}setHydrated(true);void loadRoute('Paris','Lyon','Gazole',now);return()=>{if(watchRef.current!==null&&typeof navigator!=='undefined'&&navigator.geolocation)navigator.geolocation.clearWatch(watchRef.current)}},[]);
 useEffect(()=>{if(!hydrated)return;localStorage.setItem('floway:intent',intent);localStorage.setItem('floway:vehicle',JSON.stringify(vehicle));},[intent,vehicle,hydrated]);
 function startGps(){if(typeof navigator==='undefined'||!navigator.geolocation){setGpsState('error');setGpsError('Géolocalisation non disponible sur cet appareil.');return}if(watchRef.current!==null){navigator.geolocation.clearWatch(watchRef.current);watchRef.current=null;setGpsState('off');setLive(null);return}setGpsState('requesting');setGpsError('');watchRef.current=navigator.geolocation.watchPosition(p=>{setLive({lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy,speed:p.coords.speed,updatedAt:p.timestamp});setGpsState('on')},e=>{setGpsState('error');setGpsError(e.code===1?'Autorise la localisation dans ton navigateur pour activer le mode trajet.':'Position GPS momentanément indisponible.')},{enableHighAccuracy:true,maximumAge:5000,timeout:12000});}
 // Position quantifiee a 0.05 deg (~5 km) : les deps de l'effet ne changent
 // plus a chaque tick GPS (~1 Hz), sinon l'intervalle de 30 s etait annule
 // avant de se declencher et /api/safety etait appele ~60 fois par minute.
 const safetyLat=live?Math.round(live.lat*20)/20:null,safetyLon=live?Math.round(live.lon*20)/20:null;
 useEffect(()=>{if(safetyLat===null||safetyLon===null)return;let cancelled=false;const run=async()=>{try{const latPad=.18,lonPad=.24;const u=`/api/safety?minLon=${safetyLon-lonPad}&minLat=${safetyLat-latPad}&maxLon=${safetyLon+lonPad}&maxLat=${safetyLat+latPad}`;const r=await fetch(u,{cache:'no-store'});const j=await r.json();if(cancelled)return;setSafetyConnected(Boolean(j?.provider?.connected));setSafetyIncidents(Array.isArray(j?.incidents)?j.incidents:[]);setSafetyUpdatedAt(j?.provider?.updatedAt||null);}catch{if(!cancelled){setSafetyConnected(false);setSafetyIncidents([])}}};void run();const id=window.setInterval(run,30000);return()=>{cancelled=true;window.clearInterval(id)}},[safetyLat,safetyLon]);

 const stations=useMemo(()=>[...(route?.stations||[])].sort((a,b)=>a.distanceKm-b.distanceKm),[route]);
 const liveProgress=useMemo(()=>{if(!live||!route?.geometry?.coordinates?.length)return null;const coords=route.geometry.coordinates;const cum=cumulative(coords);let idx=0,best=Infinity;for(let i=0;i<coords.length;i++){const d=haversine([live.lon,live.lat],coords[i]);if(d<best){best=d;idx=i}}return {km:Math.min(route.distanceKm,cum[idx]),offRouteKm:best,remainingKm:Math.max(0,route.distanceKm-cum[idx])}},[live,route]);
 const currentKm=liveProgress?.km||0;
 const theoreticalRange=Math.max(0,(vehicle.tankL*Math.max(0,Math.min(100,vehicle.fuelPct))/100)/Math.max(.1,vehicle.consumption)*100);
 const dynamicReserve=Math.min(vehicle.reserveKm,Math.max(15,theoreticalRange*.35));
 const usableRange=Math.max(0,theoreticalRange-dynamicReserve);
 const emergencyFuel=vehicle.fuelPct<=10||theoreticalRange<=Math.max(45,vehicle.reserveKm*.75);
 const criticalRange=Math.max(0,theoreticalRange-Math.max(10,theoreticalRange*.25));
 const fuelTargetKm=route?Math.min(route.distanceKm,Math.max(currentKm,currentKm+usableRange)):0;
 const eligible=useMemo(()=>stations.filter(s=>s.distanceKm>=currentKm&&(filter==='Tous'||s.serviceCategories?.includes(filter))),[stations,currentKm,filter]);
 const emergencyStations=useMemo(()=>eligible.filter(s=>s.distanceKm-currentKm<=criticalRange),[eligible,currentKm,criticalRange]);
 const best=useMemo(()=>{if(emergencyFuel){const pool=emergencyStations.length?emergencyStations:eligible.filter(s=>s.distanceKm-currentKm<=theoreticalRange*.92);return[...pool].sort((a,b)=>((a.distanceKm-currentKm)+a.detourMin*2)-((b.distanceKm-currentKm)+b.detourMin*2))[0]}const cat=intentCategory(intent);const preferred=intent==='Auto'||cat==='Carburant'?eligible:eligible.filter(s=>s.serviceCategories?.includes(cat));const pool=preferred.length?preferred:eligible;return[...pool].sort((a,b)=>score(a,intent)-score(b,intent))[0]},[eligible,intent,emergencyFuel,emergencyStations,currentKm,theoreticalRange]);
 const first=eligible[0]; const saved=best&&first?Math.max(0,first.waitMin+first.detourMin-best.waitMin-best.detourMin):0; const pauses=route?Math.max(0,Math.floor((route.durationMin-1)/120)):0;
 const events=useMemo(()=>{if(!route||!eligible.length)return[] as JourneyEvent[];const out:JourneyEvent[]=[];const add=(station:Station|undefined,kind:string,label?:string)=>{if(station&&!out.some(x=>x.station.id===station.id))out.push({station,kind,label:label||eventLabel(kind)});};if(emergencyFuel){add(best,'Carburant','Carburant urgent');return out}const primaryKind=intent==='Auto'?(best?.serviceCategories?.[0]||'Carburant'):intentCategory(intent);add(best,primaryKind,intent==='Manger'?'Premier arrêt · manger':undefined);const afterBest=(min=45)=>eligible.filter(s=>!best||s.distanceKm>=best.distanceKm+min);add(afterBest(55).find(s=>s.serviceCategories?.includes('Café')),'Café');if(fuelTargetKm<route.distanceKm-20){const fuelStop=eligible.reduce((a,b)=>Math.abs(b.distanceKm-fuelTargetKm)<Math.abs(a.distanceKm-fuelTargetKm)?b:a,eligible[0]);add(fuelStop,'Carburant','Ravitaillement selon autonomie');}add(afterBest(90).find(s=>s.serviceCategories?.includes('Toilettes')),'Toilettes');return out.sort((a,b)=>a.station.distanceKm-b.station.distanceKm).slice(0,5)},[eligible,best,intent,route,fuelTargetKm,emergencyFuel]);
 const nearbyIncidents=useMemo(()=>{if(!live)return[];return safetyIncidents.map(i=>({...i,distanceKm:i.lat!=null&&i.lon!=null?haversine([live.lon,live.lat],[i.lon,i.lat]):null})).filter(i=>i.distanceKm!=null&&i.distanceKm<=35).sort((a,b)=>(a.distanceKm||999)-(b.distanceKm||999)).slice(0,5)},[safetyIncidents,live]);
 const navGeometry=useMemo(()=>{const coords=route?.geometry?.coordinates||[];if(coords.length<2)return null;const sampled=coords.filter((_,i)=>i%Math.max(1,Math.floor(coords.length/90))===0||i===coords.length-1);const xs=sampled.map(c=>c[0]),ys=sampled.map(c=>c[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),dx=Math.max(.0001,maxX-minX),dy=Math.max(.0001,maxY-minY);const pts=sampled.map(c=>`${8+(c[0]-minX)/dx*84},${172-(c[1]-minY)/dy*164}`).join(' ');const progress=Math.max(0,Math.min(1,(liveProgress?.km||0)/Math.max(1,route?.distanceKm||1))),idx=Math.min(sampled.length-1,Math.round(progress*(sampled.length-1))),cp=sampled[idx];return{points:pts,x:8+(cp[0]-minX)/dx*84,y:172-(cp[1]-minY)/dy*164}},[route,liveProgress]);
 // Reference stable : OriginField la place en dependance d'un useEffect.
 const setDraftOriginStable=useCallback((v:string)=>setDraftOrigin(v),[]);
 async function submit(e:FormEvent){e.preventDefault();await loadRoute(draftOrigin.trim(),draftDestination.trim(),fuel,draftDeparture);setEditing(false)}
 const eta=route?duration(route.durationMin+pauses*15):'—'; const bestTravel=best&&route?duration(Math.max(0,Math.round((best.distanceKm-currentKm)/Math.max(route.distanceKm,1)*route.durationMin))):'—';
 const trafficLabel=route?.traffic?.label||'Trafic non connecté';
 const speedKmh=live?.speed!=null?Math.max(0,Math.round(live.speed*3.6)):0;

 return <main className="v3app">
  <header className="v3top"><button className="v3icon">☰</button><div className="v3brand"><span>≋</span><strong>Floway</strong><small>CHAQUE PAUSE COMPTE</small></div><div className="v3status"><button>🔔<b>2</b></button><span className={route?.traffic?.live?'trafficLive':'trafficOff'}>● {trafficLabel}</span><span>🌦 Météo à connecter</span></div></header>
  {error&&<div className="v3error">{error}</div>}
  <section className="v3livebar"><div><span className={gpsState==='on'?'liveDot on':'liveDot'}/><strong>{gpsState==='on'?'MODE TRAJET ACTIF':'LOCALISATION MOBILE'}</strong><small>{liveProgress?`${Math.round(liveProgress.km)} km parcourus · ${Math.round(liveProgress.remainingKm)} km restants`:gpsError||'Active le GPS pour que Floway s’adapte à ta position réelle.'}</small></div><div className="liveMeta">{live&&<><span>± {Math.round(live.accuracy)} m</span>{live.speed!=null&&<span>{speedKmh} km/h</span>}</>}</div><div className="liveActions"><button onClick={startGps}>{gpsState==='requesting'?'LOCALISATION…':gpsState==='on'?'ARRÊTER GPS':'ACTIVER GPS'}</button><button className="navLaunch" onClick={()=>{if(gpsState==='off')startGps();setNavOpen(true)}}>NAVIGATION</button></div></section>

  <section className="v3vehiclePanel"><div><span>VOTRE VÉHICULE</span><h2>{vehicle.brand} {vehicle.model} · {vehicle.year} · {vehicle.engine}</h2><small>Profil mémorisé sur cet appareil</small></div><div className="fuelGauge"><b>{vehicle.fuelPct}%</b><input aria-label="Niveau de carburant" type="range" min="0" max="100" step="1" value={vehicle.fuelPct} onChange={e=>setVehicle(v=>({...v,fuelPct:Number(e.target.value)}))}/><small>Autonomie théorique ≈ {Math.round(theoreticalRange)} km · sécurité ≈ {Math.round(usableRange)} km</small></div><button onClick={()=>setVehicleOpen(true)}>MODIFIER LE VÉHICULE</button></section>

  <section className="v3topgrid"><article className="v3hero"><div className="v3heroshade"/><div className="v3heroContent"><span className="v3hello">Bonjour 👋</span><h1>Prêt pour<br/>une belle route ?</h1><button className="v3routeTitle" title={`${origin} → ${destination}`} onClick={()=>setEditing(true)}>{placeLabel(origin)} <i>→</i> {placeLabel(destination)} <em>✎</em></button><button className="v3modifyRoute" onClick={()=>setEditing(true)}>MODIFIER L’ITINÉRAIRE</button><div className="v3heroMetrics"><div><b>{route?Math.round(route.distanceKm):'—'} km</b><small>Distance</small></div><div><b>{route?duration(route.durationMin):'—'}</b><small>Durée estimée</small></div><div><b>{pauses}</b><small>Pauses conseillées</small></div></div><div className={`v3fuelHero ${emergencyFuel?'critical':''}`}><strong>⛽ {vehicle.fuelPct}%</strong><span>{emergencyFuel?(best?`Carburant critique · arrêt conseillé dans ${Math.max(0,Math.round(best.distanceKm-currentKm))} km`:'Carburant critique · aucune station sûre identifiée sur le trajet'):fuelTargetKm&&route&&fuelTargetKm<route.distanceKm?`Ravitaillement à envisager vers ${Math.round(fuelTargetKm)} km`:'Autonomie suffisante pour ce trajet'}</span></div></div><div className="v3miniRoute"><span title={origin}>{placeLabel(origin)}</span><span title={destination}>{placeLabel(destination)}</span><div className="v3track"><i/><b className="v3car" style={liveProgress&&route?{left:`${Math.min(94,Math.max(3,liveProgress.km/route.distanceKm*100))}%`}:undefined}>🚗</b>{events.map(e=><button key={e.station.id} className="journeyMarker" style={{left:`${route?Math.min(96,Math.max(4,e.station.distanceKm/route.distanceKm*100)):50}%`}} onClick={()=>setSelected(e.station)} title={`${e.label} · ${Math.round(e.station.distanceKm)} km`}><span>{serviceIcon(e.kind)}</span><small>{Math.round(e.station.distanceKm)} km</small></button>)}<i/></div><small>{liveProgress?`${Math.round(liveProgress.km)} km`:'0 km'}</small><small>{route?Math.round(route.distanceKm):0} km</small></div></article>
   <aside className="v3feed"><div className="v3panelHead"><div><span>FIL DU VOYAGE</span><h2>Ce qui compte vraiment sur votre route</h2></div><b>{events.length} événements utiles</b></div><div className="v3vertical"><i className="v3line"/><div className="v3end"><i/><strong>{liveProgress?'Votre position':placeLabel(origin)}</strong><small>{liveProgress?`${Math.round(liveProgress.km)} km parcourus`:'0 km'}</small></div>{events.map(e=><button key={e.station.id} className={best?.id===e.station.id?'v3feedStop recommended':'v3feedStop'} onClick={()=>setSelected(e.station)}><span>{serviceIcon(e.kind)}</span><div><strong>{e.label}</strong><small>{Math.round(e.station.distanceKm)} km · {clock(e.station)} · {e.station.brand||e.station.city||e.station.name}</small></div>{best?.id===e.station.id&&<em>{emergencyFuel?'PRIORITÉ SÉCURITÉ':'FLOWAY AI ✦'}</em>}</button>)}<div className="v3end bottom"><i/><strong>{placeLabel(destination)}</strong><small>{route?Math.round(route.distanceKm):0} km · arrivée</small></div></div><button className="v3ghost" onClick={()=>document.getElementById('v3stations')?.scrollIntoView({behavior:'smooth'})}>VOIR TOUTES LES STATIONS</button></aside></section>

  <section className="v3intent"><div><span>QUE CHERCHES-TU POUR TON PROCHAIN ARRÊT ?</span><h2>{emergencyFuel?'⛽ Priorité automatique : carburant critique':intent==='Auto'?'Floway choisit selon l’heure et le trajet':intent==='Manger'?'🍴 Premier arrêt mémorisé : manger':intent==='Recharge'?'Priorité aux bornes de recharge':`Priorité mémorisée : ${intent.toLowerCase()}`}</h2></div><div className="intentChips">{(['Auto','Manger','Café','Carburant','Recharge','Toilettes'] as Intent[]).map(x=><button key={x} className={intent===x?'active':''} onClick={()=>setIntent(x)} disabled={emergencyFuel&&x!=='Carburant'}>{x==='Auto'?'✨':x==='Manger'?'🍴':x==='Café'?'☕':x==='Carburant'?'⛽':x==='Recharge'?'⚡':'🚻'} {x==='Auto'?'Floway choisit':x}</button>)}</div></section>

  <section className="v3midgrid"><article className={`v3recommend ${emergencyFuel?'fuelEmergency':''}`}><div className="v3stopImage"><span>{emergencyFuel?'⛽ ARRÊT CARBURANT PRIORITAIRE':intent==='Manger'?'🍴 ARRÊT REPAS RECOMMANDÉ':'PROCHAINE PAUSE RECOMMANDÉE'}</span><button>♡</button></div><div className="v3stopInfo"><div><h2>{best?.brand&&<small className="stationBrand">{best.brand}</small>}Aire de<br/>{best?(best.city||best.name):'—'}</h2><div className="v3services">{(best?.serviceCategories||['Carburant','Restauration','Café','Toilettes']).slice(0,7).map(s=><span key={s}><i>{serviceIcon(s)}</i>{s}</span>)}</div></div><aside><b>{best?`Dans ${Math.max(0,Math.round(best.distanceKm-currentKm))} km`:'—'}</b><strong>{bestTravel}</strong><small>{liveProgress?'depuis votre position':`depuis ${placeLabel(origin)}`}</small><ul><li>{emergencyFuel?'Le carburant passe avant toutes les autres préférences':intent==='Manger'?'Restauration obligatoire pour ce choix':intent==='Auto'?'Contexte horaire analysé':`Priorité ${intent.toLowerCase()}`}</li><li>{best?.services?.length||0} services recensés</li><li>{best?`${crowd(best.waitMin).icon} Affluence prévue ${crowd(best.waitMin).label.toLowerCase()}`:'Affluence à estimer'}</li></ul><button onClick={()=>best&&setSelected(best)}>VOIR LE DÉTAIL</button></aside></div></article>
   <article className="v3ai"><div className="v3panelHead"><div><span>FLOWAY AI</span><h2>Optimisé pour vous</h2></div><b>✦</b></div><div className="v3orb"><i/><i/><i/><strong>✦</strong></div><h3>{emergencyFuel?(best?'Votre niveau de carburant impose un arrêt maintenant.':'Votre niveau de carburant est critique.') : best?intent==='Manger'?'Votre arrêt repas est prioritaire.':'Votre meilleur arrêt est identifié.':'Floway analyse votre trajet.'}</h3><p>{emergencyFuel?(best?`Avec ${vehicle.fuelPct}% de carburant, Floway limite la recherche aux stations atteignables avec marge de sécurité. Les préférences repas et prix redeviennent actives après ravitaillement.`:'Aucune station du trajet n’est dans une zone jugée sûre avec le niveau actuel. Floway doit rechercher autour de votre position avant de poursuivre.'):(best?.smartContext?.message||'Floway croise heure de passage, position réelle, détour, affluence prédictive, carburant et services pour recommander le meilleur arrêt.')}</p><div className="v3aiStats"><div><small>AUTONOMIE SÛRE</small><b>{Math.round(usableRange)} km</b></div><div><small>DÉTOUR</small><b>{best?`+${best.detourMin} min`:'—'}</b></div><div><small>AFFLUENCE</small><b>{best?`${crowd(best.waitMin).icon} ${crowd(best.waitMin).label}`:'—'}</b></div></div></article></section>

  <section className={`v3planner vehicleLogic ${emergencyFuel?'criticalFuel':''}`}><div><span>LOGIQUE D’AUTONOMIE</span><h2>{vehicle.fuelPct}% de carburant · ≈ {Math.round(theoreticalRange)} km théoriques · ≈ {Math.round(usableRange)} km sûrs</h2><p>{emergencyFuel?'Niveau critique : Floway donne la priorité absolue à la station atteignable la plus sûre et neutralise temporairement les autres intentions.':'Le carburant reste une contrainte physique : Floway conserve toujours une marge de sécurité avant de proposer les autres besoins.'}</p></div><button onClick={()=>setVehicleOpen(true)}>RÉGLER LE NIVEAU</button><div className="v3chips">{(['Tous','Restauration','Café','Boutique','Toilettes'] as Filter[]).map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div></section>
  <section className="v3featuregrid"><article className="photo"><span>PAUSES INTELLIGENTES</span><h3>Au bon moment,<br/>pour la bonne raison.</h3></article><article><span>COMMUNAUTÉ</span><h3>À construire sans inventer<br/>de signal terrain.</h3><div className="v3communityTruth"><b>0</b><small>signalement utilisateur exploité pour l’instant</small></div></article><article><span>SÉCURITÉ ROUTIÈRE</span><h3>Incidents réels<br/>et zones de danger.</h3><div className="v3safetyState">{safetyConnected?`⚠ ${nearbyIncidents.length} incident(s) à proximité · TomTom Traffic`:'📷 Incidents / zones de danger : source à connecter ou indisponible'}</div><button className="v3ghost" onClick={()=>setNavOpen(true)}>OUVRIR LA NAVIGATION</button></article><article><span>TEMPS OPTIMISÉ</span><h3>{eta}<br/>voyage Floway</h3><strong>+{pauses*15} min de pauses utiles</strong></article></section>
  <section className="v3stations" id="v3stations"><div className="v3panelHead"><div><span>STATIONS DEVANT VOUS</span><h2>Toutes les stations</h2></div><select value={fuel} onChange={e=>{setFuel(e.target.value);void loadRoute(origin,destination,e.target.value,departure)}}><option>Gazole</option><option>SP95-E10</option><option>SP98</option><option>E85</option></select></div><div className="v3cards">{eligible.slice(0,24).map(s=><button key={s.id} onClick={()=>setSelected(s)}><span>{serviceIcon(s.serviceCategories?.[0]||'')}</span><div><strong>{s.brand||s.city||s.name}</strong><small>{Math.max(0,Math.round(s.distanceKm-currentKm))} km devant · {clock(s)}</small><em>{(s.serviceCategories||[]).slice(0,3).join(' · ')}</em></div><b>{crowd(s.waitMin).icon} {crowd(s.waitMin).label}</b></button>)}</div></section>
  <nav className="v3nav"><button className="active" onClick={()=>setNavOpen(true)}>⌁<span>NAVIGATION</span></button><button onClick={()=>document.getElementById('v3stations')?.scrollIntoView({behavior:'smooth'})}>⛽<span>STATIONS</span></button><a href="/ev">✦<span>FLOWAY AI</span></a><button>◉<span>COMMUNAUTÉ</span></button><button>○<span>PROFIL</span></button></nav>

  {navOpen&&<div className="roadNavOverlay"><section className="roadNav"><header><div><small>FLOWAY LIVE</small><strong>{placeLabel(origin)} → {placeLabel(destination)}</strong></div><button onClick={()=>setNavOpen(false)}>×</button></header><div className="roadNavMap">{navGeometry?<svg viewBox="0 0 100 180" preserveAspectRatio="none" aria-label="Tracé réel de l’itinéraire"><polyline className="roadShadow" points={navGeometry.points}/><polyline className="roadPath" points={navGeometry.points}/><circle className="roadCarHalo" cx={navGeometry.x} cy={navGeometry.y} r="5"/><circle className="roadCar" cx={navGeometry.x} cy={navGeometry.y} r="2.8"/></svg>:<div className="roadNoMap">Itinéraire en cours de chargement</div>}<div className="roadSpeed"><b>{speedKmh}</b><span>km/h GPS</span></div><div className="roadLimit"><b>—</b><span>limite</span></div>{liveProgress&&<div className="roadRemaining">{Math.round(liveProgress.remainingKm)} km restants</div>}</div><div className={`roadFuel ${emergencyFuel?'critical':''}`}><span>⛽ {vehicle.fuelPct}%</span><strong>{emergencyFuel?(best?`Arrêt carburant dans ${Math.max(0,Math.round(best.distanceKm-currentKm))} km`:'Recherche carburant urgente'):`Autonomie sûre ≈ ${Math.round(usableRange)} km`}</strong></div><div className="roadAlerts"><div className="roadSectionTitle"><span>SÉCURITÉ ROUTIÈRE</span><small>{safetyConnected?'TomTom Traffic · temps réel':'Données indisponibles'}</small></div>{nearbyIncidents.length?nearbyIncidents.map(i=><article key={i.id}><b>{i.icon}</b><div><strong>{i.label}{i.roads?.length?` · ${i.roads.join(', ')}`:''}</strong><small>{i.distanceKm!=null?`${i.distanceKm.toFixed(1)} km à proximité`:'distance inconnue'}{i.delayMin?` · +${i.delayMin} min`:''}</small><p>{i.description}</p></div></article>):<div className="roadClear">{safetyConnected?'Aucun incident TomTom détecté dans la zone surveillée.':'Aucune alerte affichée tant qu’une source réelle n’est pas disponible.'}</div>}<div className="roadDangerTruth">📷 Zones de danger / radars : aucune donnée inventée. Source dédiée encore à connecter.</div></div><footer><span>{gpsState==='on'?'● GPS actif':'○ GPS inactif'}</span><span>± {live?Math.round(live.accuracy):'—'} m</span><span>{safetyUpdatedAt?`maj ${new Date(safetyUpdatedAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}`:'sécurité non mise à jour'}</span></footer></section></div>}

  {editing&&<div className="v3overlay" onClick={()=>!loading&&setEditing(false)}><form className="v3modal" onSubmit={submit} onClick={e=>e.stopPropagation()}><span>NOUVEL ITINÉRAIRE</span><h2>Où va-t-on ?</h2><OriginField value={draftOrigin} onChange={setDraftOriginStable} disabled={loading}/><label>Destination<input value={draftDestination} onChange={e=>setDraftDestination(e.target.value)} required/></label><label>Heure de départ<input type="datetime-local" value={draftDeparture} onChange={e=>setDraftDeparture(e.target.value)} required/></label><button disabled={loading}>{loading?'ANALYSE…':'ANALYSER LE TRAJET →'}</button></form></div>}

  {vehicleOpen&&<div className="v3overlay" onClick={()=>setVehicleOpen(false)}><form className="v3modal vehicleModal" onSubmit={e=>{e.preventDefault();setVehicleOpen(false)}} onClick={e=>e.stopPropagation()}><span>PROFIL VÉHICULE MÉMORISÉ</span><h2>Votre voiture</h2><div className="vehicleFields"><label>Marque<input value={vehicle.brand} onChange={e=>setVehicle(v=>({...v,brand:e.target.value}))}/></label><label>Modèle<input value={vehicle.model} onChange={e=>setVehicle(v=>({...v,model:e.target.value}))}/></label><label>Année<input value={vehicle.year} onChange={e=>setVehicle(v=>({...v,year:e.target.value}))}/></label><label>Motorisation<input value={vehicle.engine} onChange={e=>setVehicle(v=>({...v,engine:e.target.value}))}/></label><label>Réservoir (L)<input type="number" min="10" max="150" value={vehicle.tankL} onChange={e=>setVehicle(v=>({...v,tankL:Number(e.target.value)}))}/></label><label>Conso (L/100)<input type="number" min="2" max="30" step="0.1" value={vehicle.consumption} onChange={e=>setVehicle(v=>({...v,consumption:Number(e.target.value)}))}/></label><label>Niveau actuel (%)<input type="number" min="0" max="100" value={vehicle.fuelPct} onChange={e=>setVehicle(v=>({...v,fuelPct:Number(e.target.value)}))}/></label><label>Réserve sécurité (km)<input type="number" min="20" max="200" value={vehicle.reserveKm} onChange={e=>setVehicle(v=>({...v,reserveKm:Number(e.target.value)}))}/></label></div><button>ENREGISTRER →</button></form></div>}

  {selected&&<div className="v3overlay" onClick={()=>setSelected(null)}><article className="v3detail" onClick={e=>e.stopPropagation()}><button className="v3close" onClick={()=>setSelected(null)}>←</button><div className="v3detailImage"><span>FICHE ARRÊT FLOWAY</span></div><div className="v3detailBody"><span className="detailEyebrow">STATION / AIRE SUR VOTRE ITINÉRAIRE</span><h2>{selected.brand&&<small className="stationBrand">{selected.brand}</small>}{selected.name}</h2><p>{selected.address&&`${selected.address} · `}{selected.city} · {Math.max(0,Math.round(selected.distanceKm-currentKm))} km devant · passage {clock(selected)}</p><div className="v3detailStats"><div><small>AFFLUENCE PRÉVUE</small><b>{crowd(selected.waitMin).icon} {crowd(selected.waitMin).label}</b></div><div><small>PRIX {fuel.toUpperCase()}</small><b>{selected.price?`${selected.price.toFixed(3)} €/L`:'—'}</b></div><div><small>DÉTOUR</small><b>+{selected.detourMin} min</b></div></div><p className="predictionTruth">L’affluence est une prédiction Floway, pas une mesure de file d’attente en temps réel.</p><h3 className="detailSectionTitle">SERVICES DISPONIBLES</h3><div className="v3services rich">{(selected.serviceCategories||[]).map(s=><span key={s}><i>{serviceIcon(s)}</i>{s}</span>)}</div>{selected.services?.length?<><h3 className="detailSectionTitle">DÉTAIL DES SERVICES RECENSÉS</h3><div className="rawServices">{selected.services.map(s=><span key={s}>{s}</span>)}</div></>:null}<div className="restaurantCallout"><div>🍴</div><div><strong>La restauration peut décider de l’arrêt</strong><p>{selected.serviceCategories?.includes('Restauration')?'Cette aire dispose d’une offre de restauration recensée. Floway la valorise davantage si votre priorité est de manger.':'Aucune restauration détaillée n’est encore recensée ici : Floway ne la choisira pas en premier si votre priorité est de manger.'}</p></div></div><div className="v3detailAI"><span>FLOWAY AI ✦</span><p>{selected.smartContext?.message||'Cet arrêt est analysé selon votre heure de passage, votre position, le détour, l’affluence prédictive et les services disponibles.'}</p>{selected.waitModel?.factors?.length?<ul>{selected.waitModel.factors.map(f=><li key={f}>{f}</li>)}</ul>:null}</div>{selected.sources&&<div className="detailSources"><small>Données station : {selected.sources.station||'source publique'}</small><small>Prix : {selected.sources.priceFreshness||'mise à jour disponible'}</small><small>Affluence : {selected.sources.wait||'estimation Floway'}</small></div>}<button className="v3choose" onClick={()=>setSelected(null)}>CHOISIR CET ARRÊT →</button></div></article></div>}
 </main>
}
