'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { RESTAURANT_BRANDS, loadRestaurantPreferences, saveRestaurantPreferences, type RestaurantBrand } from './restaurant-preferences';

type Pos={lat:number;lon:number;speed:number|null;heading:number|null;accuracy:number;at:number};
type Step={id:string;distanceM:number;durationSec:number;roadName?:string|null;roadRef?:string|null;exit?:string|null;type?:string|null;instruction:string;icon:string;location?:{lat:number;lon:number}|null};
type Area={id:string;name:string;kind:'service'|'rest';distanceKm:number;routeOffsetKm:number;lat:number;lon:number;operator?:string|null;services:string[];restaurants:string[];source:string};
type LiveRoute={distanceKm:number;durationMin:number;geometry:{coordinates:[number,number][]};steps:Step[];areas:Area[];destination:{label:string};generatedAt:string};

const rad=(n:number)=>n*Math.PI/180;
function hav(a:[number,number],b:[number,number]){const R=6371,dLat=rad(b[1]-a[1]),dLon=rad(b[0]-a[0]),la1=rad(a[1]),la2=rad(b[1]);const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h));}
function cumulative(c:[number,number][]){const out=[0];for(let i=1;i<c.length;i++)out[i]=out[i-1]+hav(c[i-1],c[i]);return out;}
function destinationFromDom(){const b=document.querySelector<HTMLButtonElement>('.v3routeTitle');const t=b?.textContent?.replace(/\s+/g,' ').trim()||'';const p=t.split('→').map(x=>x.replace('✎','').trim()).filter(Boolean);return p.length>=2?p[p.length-1]:null;}
function eta(route:LiveRoute|null,km:number){if(!route?.distanceKm||!route.durationMin)return'--:--';const mins=Math.max(1,Math.round(km/route.distanceKm*route.durationMin));const d=new Date(Date.now()+mins*60000);return `${d.toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})} · ~${mins} min`;}
function localPath(route:LiveRoute|null,aheadKm:number){const c=route?.geometry?.coordinates;if(!c?.length)return null;const cum=cumulative(c),pts=c.filter((_,i)=>cum[i]<=aheadKm);if(pts.length<2)return null;const origin=pts[0],lat0=rad(origin[1]);const local=pts.map(p=>({x:(p[0]-origin[0])*111.32*Math.cos(lat0),y:(p[1]-origin[1])*110.57}));const ref=local[Math.min(local.length-1,Math.max(1,local.findIndex(p=>Math.hypot(p.x,p.y)>=.25)))];const angle=Math.atan2(ref.x,ref.y);const rot=local.map(p=>({x:p.x*Math.cos(angle)-p.y*Math.sin(angle),y:p.x*Math.sin(angle)+p.y*Math.cos(angle)}));const maxX=Math.max(1,...rot.map(p=>Math.abs(p.x))),maxY=Math.max(.3,...rot.map(p=>p.y));return rot.map(p=>`${50+(p.x/maxX)*34},${160-(p.y/maxY)*138}`).join(' ');}

export default function LiveCopilotLayer(){
 const [open,setOpen]=useState(false),[food,setFood]=useState(false),[selectedArea,setSelectedArea]=useState<Area|null>(null);
 const [destination,setDestination]=useState<string|null>(null),[route,setRoute]=useState<LiveRoute|null>(null),[pos,setPos]=useState<Pos|null>(null);
 const [limit,setLimit]=useState<number|null>(null),[road,setRoad]=useState(''),[prefs,setPrefs]=useState<RestaurantBrand[]>([]),[routeState,setRouteState]=useState('GPS en attente');
 const watch=useRef<number|null>(null),previous=useRef<Pos|null>(null),lastRouteAt=useRef(0),lastRoutePos=useRef<Pos|null>(null);

 useEffect(()=>{setPrefs(loadRestaurantPreferences());const sync=()=>{const d=destinationFromDom();if(d)setDestination(d)};sync();const id=setInterval(sync,1500);return()=>clearInterval(id)},[]);
 useEffect(()=>{const click=(e:MouseEvent)=>{const t=e.target as HTMLElement|null;if(t?.closest('.navLaunch,.v3nav button:first-child,[data-floway-live-nav]')){e.preventDefault();e.stopPropagation();setOpen(true)}};document.addEventListener('click',click,true);return()=>document.removeEventListener('click',click,true)},[]);
 useEffect(()=>{if(!open||!navigator.geolocation||watch.current!==null)return;watch.current=navigator.geolocation.watchPosition(p=>{const n:Pos={lat:p.coords.latitude,lon:p.coords.longitude,speed:p.coords.speed,heading:p.coords.heading,accuracy:p.coords.accuracy,at:p.timestamp};const old=previous.current;previous.current=n;setPos(n);try{localStorage.setItem('floway:last-position',JSON.stringify(n))}catch{};if(old){const u=`/api/speed-limit?lat1=${old.lat}&lon1=${old.lon}&lat2=${n.lat}&lon2=${n.lon}${Number.isFinite(n.heading)?`&heading=${n.heading}`:''}`;fetch(u,{cache:'no-store'}).then(r=>r.json()).then(j=>{setLimit(typeof j?.speedLimit==='number'?Math.round(j.speedLimit):null);setRoad([...(j?.roadNumbers||[]),j?.roadName].filter(Boolean).join(' · '))}).catch(()=>{})}},()=>setRouteState('GPS indisponible'),{enableHighAccuracy:true,maximumAge:1000,timeout:12000});return()=>{if(watch.current!==null){navigator.geolocation.clearWatch(watch.current);watch.current=null}},[open]);
 useEffect(()=>{if(!open||!pos||!destination)return;const moved=lastRoutePos.current?hav([lastRoutePos.current.lon,lastRoutePos.current.lat],[pos.lon,pos.lat]):999;if(Date.now()-lastRouteAt.current<35000&&moved<.8)return;lastRouteAt.current=Date.now();lastRoutePos.current=pos;setRouteState('Recalcul depuis votre position…');fetch(`/api/live-navigation?lat=${pos.lat}&lon=${pos.lon}&destination=${encodeURIComponent(destination)}`,{cache:'no-store'}).then(r=>r.json()).then(j=>{if(j?.geometry?.coordinates&&Array.isArray(j?.steps)){setRoute(j);setRouteState('Itinéraire recalé sur votre GPS');try{localStorage.setItem('floway:active-session',JSON.stringify({origin:'Ma position',destination,navOpen:true,updatedAt:Date.now()}))}catch{}}else setRouteState('Itinéraire temporairement indisponible')}).catch(()=>setRouteState('Itinéraire temporairement indisponible'))},[open,pos?.lat,pos?.lon,destination]);

 const speed=Math.max(0,Math.round((pos?.speed||0)*3.6)),aheadKm=Math.max(2.5,Math.min(9,(Math.max(speed,50)/60)*3));
 const path=useMemo(()=>localPath(route,aheadKm),[route,aheadKm]);
 const next=useMemo(()=>route?.steps?.find(s=>s.type!=='depart'&&s.distanceM>20)||route?.steps?.[1]||route?.steps?.[0]||null,[route]);
 const areas=useMemo(()=>[...(route?.areas||[])].filter(a=>a.distanceKm>=0).sort((a,b)=>a.distanceKm-b.distanceKm).slice(0,5),[route]);
 function togglePref(b:RestaurantBrand){setPrefs(prev=>{const n=prev.includes(b)?prev.filter(x=>x!==b):[...prev,b];saveRestaurantPreferences(n);return n})}

 if(!open)return null;
 return <div className="copilotOverlay"><section className="copilotShell">
  <header><div><small>FLOWAY COPILOTE · LIVE</small><strong>{road||'Route en cours d’identification'}</strong><span>{destination?`vers ${destination}`:'Choisissez une destination'} · {routeState}</span></div><button onClick={()=>setOpen(false)}>×</button></header>
  <div className="copilotMap">{path?<svg viewBox="0 0 100 180" preserveAspectRatio="none"><polyline className="copilotShadow" points={path}/><polyline className="copilotRoad" points={path}/><circle cx="50" cy="150" r="4.2" className="copilotHalo"/><circle cx="50" cy="150" r="2.5" className="copilotCar"/></svg>:<div className="copilotWaiting">{destination?'Calcul de la route depuis votre position GPS…':'Définissez une destination pour lancer le guidage.'}</div>}<div className={`copilotSpeed ${limit&&speed>limit+4?'over':''}`}><b>{speed}</b><span>km/h</span></div><div className="copilotLimit"><b>{limit??'—'}</b><span>limite</span></div><div className="copilotHorizon">≈ 3 min devant · {aheadKm.toFixed(1)} km</div></div>
  <div className="copilotInstruction"><div className="turnIcon">{next?.icon||'↑'}</div><div><small>PROCHAINE INSTRUCTION</small><strong>{next?.instruction||'Calcul du guidage en cours'}</strong><span>{next?`${next.distanceM<1000?`${next.distanceM} m`:`${(next.distanceM/1000).toFixed(1)} km`}${next.exit?` · sortie ${next.exit}`:''}`:'—'}</span></div></div>

  <div className="motorwayAreaBlock"><div className="motorwayAreaHead"><div><small>AIRES D’AUTOROUTE</small><strong>Les prochaines aires officielles de la route</strong></div><span>BLEU AUTOROUTE</span></div>{areas.length?areas.map((a,i)=><button className="motorwayAreaCard" key={a.id} onClick={()=>setSelectedArea(a)}><div className="motorwayShield">AIRE</div><div><small>{i===0?'PROCHAINE AIRE':'AIRE À VENIR'}</small><strong>{a.name}</strong><span>Dans {a.distanceKm.toFixed(a.distanceKm<10?1:0)} km · {eta(route,a.distanceKm)}</span><em>{a.restaurants.length?`🍴 ${a.restaurants.slice(0,3).join(' · ')}`:a.services.length?a.services.slice(0,4).join(' · '):'Services à ouvrir'}</em></div><b>›</b></button>):<div className="motorwayAreaEmpty">Aucune aire autoroutière nommée n’est encore remontée sur la portion analysée. Les stations ordinaires restent séparées.</div>}</div>

  <div className="copilotActions"><button className={food?'active':''} onClick={()=>setFood(v=>!v)}>🍴 RESTAURANTS</button><button onClick={()=>{setOpen(false);setTimeout(()=>document.getElementById('v3stations')?.scrollIntoView({behavior:'smooth'}),80)}}>⛽ AUTRES STATIONS</button></div>
  {food&&<div className="copilotFood"><div className="foodHead"><div><small>MES ENSEIGNES PRÉFÉRÉES</small><strong>Filtrer les restaurants trouvés dans les prochaines aires</strong></div></div><div className="copilotBrandChips">{RESTAURANT_BRANDS.map(b=><button key={b} className={prefs.includes(b)?'active':''} onClick={()=>togglePref(b)}>{prefs.includes(b)?'✓ ':''}{b}</button>)}</div>{areas.map(a=>{const hits=a.restaurants.filter(r=>!prefs.length||prefs.some(p=>r.toLowerCase().includes(p.toLowerCase())));return <article key={a.id}><b>🛣️</b><div><strong>{a.name}</strong><span>Dans {a.distanceKm.toFixed(a.distanceKm<10?1:0)} km · {eta(route,a.distanceKm)}</span><em>{hits.length?`★ ${hits.join(' · ')}`:a.restaurants.length?a.restaurants.join(' · '):'Enseigne non confirmée'}</em></div></article>})}</div>}
  <footer><span>GPS {pos?`±${Math.round(pos.accuracy)} m`:'en attente'}</span><span>{route?`${Math.round(route.distanceKm)} km restants`:'—'}</span><span>{route?'route recalculée en arrière-plan':'route non calculée'}</span></footer>

  {selectedArea&&<div className="areaDetailBackdrop" onClick={()=>setSelectedArea(null)}><article className="areaDetail" onClick={e=>e.stopPropagation()}><button className="areaDetailClose" onClick={()=>setSelectedArea(null)}>×</button><span>AIRE D’AUTOROUTE</span><h2>{selectedArea.name}</h2><p>Dans {selectedArea.distanceKm.toFixed(1)} km · arrivée estimée {eta(route,selectedArea.distanceKm)}</p><div className="areaDetailRows"><div><small>TYPE</small><b>{selectedArea.kind==='service'?'Aire de services':'Aire de repos'}</b></div><div><small>OPÉRATEUR</small><b>{selectedArea.operator||'Non renseigné'}</b></div><div><small>ÉCART ROUTE</small><b>{selectedArea.routeOffsetKm.toFixed(1)} km</b></div></div><h3>Restaurants</h3><div className="areaPills">{selectedArea.restaurants.length?selectedArea.restaurants.map(x=><span key={x}>🍴 {x}</span>):<span>Enseignes non encore confirmées</span>}</div><h3>Services</h3><div className="areaPills">{selectedArea.services.length?selectedArea.services.map(x=><span key={x}>{x}</span>):<span>Services à enrichir</span>}</div><small className="areaSource">Source actuelle : {selectedArea.source}. Floway distingue ces aires des stations ordinaires hors autoroute.</small></article></div>}
 </section></div>;
}
