'use client';

import { useEffect } from 'react';

type Fuel={key:string;label:string;price:number;updatedAt:string|null;ageHours:number|null;freshness:string};
type FuelResponse={source?:string;official?:boolean;station?:{address?:string;city?:string}|null;fuels?:Fuel[];message?:string};
function ageLabel(f:Fuel){if(f.ageHours==null)return'Mise à jour inconnue';if(f.ageHours<1)return'Mis à jour il y a moins d’1 h';if(f.ageHours<24)return`Mis à jour il y a ${Math.round(f.ageHours)} h`;return`Mis à jour il y a ${Math.round(f.ageHours/24)} j`;}
function badge(f:Fuel){return f.freshness==='récente'?'fresh':f.freshness==='à vérifier'?'aging':f.freshness==='ancienne'?'old':'unknown';}
export default function StationFuelLayer(){useEffect(()=>{let active=true;const observer=new MutationObserver(async()=>{const detail=document.querySelector('.v3detail');if(!detail||detail.querySelector('[data-floway-fuels]'))return;const title=detail.querySelector('h2')?.textContent?.trim();const meta=detail.querySelector('.v3detailBody > p')?.textContent?.trim();if(!title)return;const mount=document.createElement('section');mount.setAttribute('data-floway-fuels','loading');mount.className='stationFuelPanel';mount.innerHTML='<div class="fuelPanelHead"><span>PRIX CARBURANTS</span><small>Chargement des prix officiels…</small></div>';const anchor=detail.querySelector('.v3detailStats');anchor?.insertAdjacentElement('afterend',mount);try{const q=[title,meta?.split('·')[0]].filter(Boolean).join(' ');const r=await fetch(`/api/station-fuels?q=${encodeURIComponent(q)}`,{cache:'no-store'});const data=await r.json() as FuelResponse;if(!active||!mount.isConnected)return;if(!r.ok)throw new Error('Prix indisponibles');const fuels=data.fuels||[];mount.setAttribute('data-floway-fuels','ready');mount.innerHTML=`<div class="fuelPanelHead"><div><span>PRIX CARBURANTS</span><strong>${data.official?'Données officielles':'Source disponible'}</strong></div><small>${data.source||'Source carburants'}</small></div>${fuels.length?`<div class="fuelGrid">${fuels.map(f=>`<article class="fuelCard ${badge(f)}"><div><strong>${f.label}</strong><small>${ageLabel(f)}</small></div><b>${f.price.toFixed(3)} <em>€/L</em></b><span>${f.freshness}</span></article>`).join('')}</div>`:`<p class="fuelEmpty">${data.message||'Aucun prix disponible pour cette station.'}</p>`}`;}catch{if(mount.isConnected)mount.innerHTML='<div class="fuelPanelHead"><span>PRIX CARBURANTS</span><small>Prix momentanément indisponibles.</small></div>';}});observer.observe(document.body,{childList:true,subtree:true});return()=>{active=false;observer.disconnect()};},[]);return null;}
