import { NextRequest, NextResponse } from 'next/server';

import { timeoutFetch, SLOW_TIMEOUT_MS } from '../_lib/http';

// Masque le `fetch` global pour ce module : tout appel sortant est abandonné
// automatiquement au-delà du délai, sans modifier les points d'appel.
const fetch = timeoutFetch(SLOW_TIMEOUT_MS);

type Point=[number,number];
type GeoFeature={geometry?:{coordinates?:Point};properties?:{label?:string}};
type OsmElement={type:string;id:number;lat?:number;lon?:number;center?:{lat:number;lon:number};tags?:Record<string,string>};

const rad=(n:number)=>n*Math.PI/180;
function hav(a:Point,b:Point){const R=6371,dLat=rad(b[1]-a[1]),dLon=rad(b[0]-a[0]),la1=rad(a[1]),la2=rad(b[1]);const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h));}
function cumulative(c:Point[]){const out=[0];for(let i=1;i<c.length;i++)out[i]=out[i-1]+hav(c[i-1],c[i]);return out;}
async function geocode(q:string){const u=new URL('https://data.geopf.fr/geocodage/search');u.searchParams.set('q',q);u.searchParams.set('limit','1');u.searchParams.set('returntruegeometry','false');const r=await fetch(u,{headers:{Accept:'application/json'},next:{revalidate:86400}});if(!r.ok)throw new Error('GEOCODING_FAILED');const d=await r.json() as {features?:GeoFeature[]};const f=d.features?.[0],c=f?.geometry?.coordinates;if(!c)throw new Error('PLACE_NOT_FOUND');return{lon:c[0],lat:c[1],label:f?.properties?.label||q};}
function icon(type?:string,modifier?:string){if(type==='arrive')return'🏁';if(type==='roundabout'||type==='rotary')return'↻';if(type==='merge'||type==='on ramp'||type==='off ramp'||type==='fork')return modifier?.includes('left')?'↖':'↗';if(modifier?.includes('left'))return'←';if(modifier?.includes('right'))return'→';if(modifier==='uturn')return'↩';return'↑';}
function instruction(s:any){const m=s.maneuver||{},road=[s.ref,s.name].filter(Boolean).join(' · ')||'la route',dest=s.destinations?` direction ${s.destinations}`:'',exit=s.exits?` sortie ${s.exits}`:'';if(m.type==='arrive')return'Vous êtes arrivé à destination';if(m.type==='merge')return`Insérez-vous sur ${road}${dest}`;if(m.type==='on ramp')return`Prenez la bretelle vers ${road}${dest}`;if(m.type==='off ramp')return`Prenez${exit} vers ${road}${dest}`;if(m.type==='fork')return`Restez ${m.modifier?.includes('left')?'à gauche':'à droite'} vers ${road}${dest}`;if(m.type==='roundabout'||m.type==='rotary')return`Au rond-point, continuez vers ${road}${dest}`;if(m.type==='turn')return`Tournez ${m.modifier?.includes('left')?'à gauche':m.modifier?.includes('right')?'à droite':''} sur ${road}${dest}`.replace('  ',' ');return`Continuez sur ${road}${dest}`;}
function elementPoint(e:OsmElement):Point|null{const lat=e.lat??e.center?.lat,lon=e.lon??e.center?.lon;return typeof lat==='number'&&typeof lon==='number'?[lon,lat]:null;}
function serviceLabel(tags:Record<string,string>={}){const amenity=tags.amenity||'';if(amenity==='fuel')return'Carburant';if(amenity==='restaurant')return'Restaurant';if(amenity==='fast_food')return'Restauration rapide';if(amenity==='cafe')return'Café';if(amenity==='toilets')return'Toilettes';if(amenity==='charging_station')return'Recharge VE';return null;}
async function motorwayAreas(coords:Point[]){const cum=cumulative(coords),limitKm=Math.min(130,cum.at(-1)||0);let end=coords.length-1;for(let i=0;i<cum.length;i++){if(cum[i]>=limitKm){end=i;break;}}const sample=coords.slice(0,end+1);const xs=sample.map(p=>p[0]),ys=sample.map(p=>p[1]);const pad=.045,bbox=[Math.min(...ys)-pad,Math.min(...xs)-pad,Math.max(...ys)+pad,Math.max(...xs)+pad];const q=`[out:json][timeout:18];(nwr[\"highway\"~\"^(services|rest_area)$\"](${bbox.join(',')});nwr[\"amenity\"~\"^(fuel|restaurant|fast_food|cafe|toilets|charging_station)$\"](${bbox.join(',')}););out center tags;`;try{const r=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:`data=${encodeURIComponent(q)}`,cache:'no-store'});if(!r.ok)throw new Error(`OVERPASS_${r.status}`);const d=await r.json() as {elements?:OsmElement[]};const elements=d.elements||[],areas=elements.filter(e=>/^(services|rest_area)$/.test(e.tags?.highway||'')),amenities=elements.filter(e=>e.tags?.amenity);const projected=areas.map((a,index)=>{const p=elementPoint(a);if(!p)return null;let idx=0,off=Infinity;for(let i=0;i<sample.length;i++){const dist=hav(p,sample[i]);if(dist<off){off=dist;idx=i;}}if(off>2.2)return null;const nearby=amenities.map(e=>({e,p:elementPoint(e)})).filter(x=>x.p&&hav(p,x.p!)<=1).map(x=>x.e);const services=[...new Set(nearby.map(e=>serviceLabel(e.tags)).filter(Boolean))] as string[];const restaurants=[...new Set(nearby.filter(e=>['restaurant','fast_food','cafe'].includes(e.tags?.amenity||'')).map(e=>e.tags?.brand||e.tags?.name).filter(Boolean))] as string[];return{id:`${a.type}-${a.id}`,name:a.tags?.name||a.tags?.['name:fr']||`Aire autoroutière ${index+1}`,kind:a.tags?.highway==='services'?'service':'rest',distanceKm:Math.round(cum[idx]*10)/10,routeOffsetKm:Math.round(off*10)/10,lat:p[1],lon:p[0],operator:a.tags?.operator||null,services,restaurants,source:'OpenStreetMap · highway=services/rest_area'};}).filter(Boolean) as any[];return projected.sort((a,b)=>a.distanceKm-b.distanceKm).slice(0,10);}catch{return[];}}

export async function GET(req:NextRequest){const q=req.nextUrl.searchParams,destination=q.get('destination')?.trim(),lat=Number(q.get('lat')),lon=Number(q.get('lon'));if(!destination||!Number.isFinite(lat)||!Number.isFinite(lon))return NextResponse.json({error:'Position GPS et destination requises.'},{status:400});try{const to=await geocode(destination);const u=`https://router.project-osrm.org/route/v1/driving/${lon},${lat};${to.lon},${to.lat}?alternatives=false&steps=true&overview=full&geometries=geojson&annotations=false`;const r=await fetch(u,{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error('ROUTING_FAILED');const d=await r.json();const route=d.routes?.[0],leg=route?.legs?.[0];if(!route||!leg)throw new Error('NO_ROUTE');const coords=route.geometry?.coordinates as Point[]|undefined;if(!coords?.length)throw new Error('NO_GEOMETRY');const [areas]=await Promise.all([motorwayAreas(coords)]);const steps=(leg.steps||[]).map((s:any,index:number)=>({id:`step-${index}`,order:index,distanceM:Math.round(s.distance||0),durationSec:Math.round(s.duration||0),roadName:s.name||null,roadRef:s.ref||null,destinations:s.destinations||null,exit:s.exits||null,type:s.maneuver?.type||null,modifier:s.maneuver?.modifier||null,location:s.maneuver?.location?{lon:s.maneuver.location[0],lat:s.maneuver.location[1]}:null,icon:icon(s.maneuver?.type,s.maneuver?.modifier),instruction:instruction(s)}));const durationMin=Math.max(1,Math.round(route.duration/60)),distanceKm=Math.round(route.distance/100)/10;return NextResponse.json({provider:{routing:'OSRM',areas:'OpenStreetMap'},origin:{label:'Ma position',lat,lon},destination:to,distanceKm,durationMin,geometry:route.geometry,steps,areas,generatedAt:new Date().toISOString()});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'LIVE_NAVIGATION_ERROR'},{status:502});}}
